### ISSUE TITLE
Evince pdf viewer does not reload an opened PDF after a mnogoo run

### ISSUE THREAD

**Issue by tetrapharmakon** [paolobrasolin/mnogootex#6]

**Comment by paolobrasolin** [comment]
Ok, the problem is https://github.com/paolobrasolin/mnogootex/blob/e8c19bd9c88e07365f8c3cc834417f6ec9eba6d9/lib/mnogootex/job/warden.rb#L47

That is, before a run all output files are deleted and viewers lose track of them so they cannot autoreload.

That was the initial design to avoid making any kind of assumption about the build command and always starting fresh.

Perhaps subtlety would be more suitable:
* don't remove anything automatically (which might be good to speed up the typical build)
* define `mnogootex clean` to remove aux files
* define `mnogootex clobber` to remove aux files + final documents
* define `mnogootex nuclear` to remove everything, source included (that's what `mnogootex clean` currently does)

**Comment by paolobrasolin** [comment]
@tetrapharmakon solved in v2! :confetti_ball:
